{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPJ87jBPVfNARrdr+ChehMb"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "74XeY9k6FMKG"
      },
      "outputs": [],
      "source": [
        "import os\n",
        "import json\n",
        "import platform\n",
        "import webbrowser\n",
        "import zipfile\n",
        "import tkinter as tk\n",
        "from tkinter import filedialog, messagebox, ttk\n",
        "\n",
        "CONFIG_FILE = os.path.join(os.path.expanduser(\"~\"), \".sims4_manager.json\")\n",
        "KRISTINA_MEDIAFIRE = \"https://www.mediafire.com/folder/3sc6iawzv7ysu/TS4+Resources\"\n",
        "YOUTUBE_LINK = \"https://www.youtube.com/@KristinaPlaysTheSims/featured\"\n",
        "LEUANS_SERVER = \"https://discord.gg/G7eMu58YAK\"\n",
        "MELON_ARCHIVE = \"https://gofile.io/d/VqC3pX\"\n",
        "\n",
        "_SYS = platform.system()\n",
        "FONT = \"Helvetica Neue\" if _SYS == \"Darwin\" else (\"Segoe UI\" if _SYS == \"Windows\" else \"DejaVu Sans\")\n",
        "\n",
        "C = {\n",
        "    \"bg\":           \"#ffd6ea\",\n",
        "    \"fg\":           \"#000000\",\n",
        "    \"accent\":       \"#ff4daf\",\n",
        "    \"accent_h\":     \"#ff63ac\",\n",
        "    \"error\":        \"#fc728d\",\n",
        "    \"success\":      \"#8fffa3\",\n",
        "    \"warning\":      \"#fcc46f\",\n",
        "    \"card\":         \"#ff91ca\",\n",
        "    \"border\":       \"#e84a9e\",\n",
        "    \"muted\":        \"#050505\",\n",
        "    \"desc\":         \"#050505\",\n",
        "}\n",
        "\n",
        "PAD = 28   # horizontal page padding\n",
        "\n",
        "# ==================== TRANSLATIONS ====================\n",
        "T = {\n",
        "    \"es\": {\n",
        "        \"title\": \"The Sims 4 - Content Manager (Original by Leuan)\",\n",
        "        \"language\": \"Idioma\",\n",
        "        \"select_folder\": \"Seleccionar carpeta\",\n",
        "        \"path_label\": \"Ruta del juego:\",\n",
        "        \"start\": \"Iniciar instalación\",\n",
        "        \"mode_select\": \"Modo de instalación\",\n",
        "        \"mode_single\": \"Instalar un archivo\",\n",
        "        \"mode_all\": \"Instalar todos los DLCs\",\n",
        "        \"mode_offline\": \"Modo Offline (backup)\",\n",
        "        \"step_1\": \"Paso 1 — Descarga el archivo\",\n",
        "        \"step_1_desc\": \"Haz clic en el botón de abajo para abrir el enlace de descarga y descargar el archivo .zip.\",\n",
        "        \"step_2\": \"Paso 2 — Selecciona el archivo .zip\",\n",
        "        \"step_2_desc\": \"Una vez descargado, haz clic en el botón y elige el archivo .zip.\",\n",
        "        \"step_3\": \"Paso 3 — Selecciona la carpeta del juego\",\n",
        "        \"step_3_desc\": \"Haz clic en el botón y elige la carpeta donde está instalado The Sims 4.\",\n",
        "        \"dlc_steps_1\": \"Paso 1 — Descarga todos los DLCs\",\n",
        "        \"dlc_steps_1_desc\": \"Haz clic en el botón y descarga TODOS los archivos .zip de DLC.\",\n",
        "        \"dlc_steps_2\": \"Paso 2 — Guárdalos en una sola carpeta\",\n",
        "        \"dlc_steps_2_desc\": \"Guarda TODOS los archivos .zip descargados dentro de UNA SOLA CARPETA en tu computadora.\",\n",
        "        \"dlc_steps_3\": \"Paso 3 — Selecciona la carpeta de DLCs\",\n",
        "        \"dlc_steps_3_desc\": \"Haz clic en el botón y elige la carpeta donde guardaste todos los .zip.\",\n",
        "        \"dlc_steps_4\": \"Paso 4 — Selecciona la carpeta del juego\",\n",
        "        \"dlc_steps_4_desc\": \"Haz clic en el botón y elige la carpeta donde está instalado The Sims 4.\",\n",
        "        \"offline_title\": \"Modo Offline\",\n",
        "        \"offline_desc\": \"Instala directamente desde tu backup local. No necesitas internet ni enlaces de descarga.\",\n",
        "        \"offline_step_1\": \"Paso 1 — Selecciona la carpeta de backup\",\n",
        "        \"offline_step_1_desc\": \"Elige la carpeta donde guardaste todos tus archivos .zip de backup.\",\n",
        "        \"offline_step_2\": \"Paso 2 — Selecciona la carpeta del juego\",\n",
        "        \"offline_step_2_desc\": \"Elige la carpeta donde está instalado The Sims 4.\",\n",
        "        \"zip_label\": \"Archivo .zip seleccionado:\",\n",
        "        \"dlc_folder_label\": \"Carpeta de DLCs:\",\n",
        "        \"backup_label\": \"Carpeta de backup:\",\n",
        "        \"zip_ph\": \"Ningún archivo seleccionado\",\n",
        "        \"path_ph\": \"Ninguna ruta seleccionada\",\n",
        "        \"folder_ph\": \"Ninguna carpeta seleccionada\",\n",
        "        \"backup_ph\": \"No configurado aún\",\n",
        "        \"open_link\": \"🌐  Abrir enlace de descarga\",\n",
        "        \"browse_dlcs\": \"📁  Explorar carpeta DLC\",\n",
        "        \"browse_game\": \"📂  Seleccionar carpeta del juego\",\n",
        "        \"browse_zip\": \"📄  Seleccionar archivo .zip\",\n",
        "        \"browse_backup\": \"📦  Seleccionar carpeta de backup\",\n",
        "        \"install_all\": \"⚙️  Instalar todos los DLCs\",\n",
        "        \"install_from_backup\": \"⚙️  Instalar desde backup\",\n",
        "        \"error\": \"Error\",\n",
        "        \"success\": \"Éxito\",\n",
        "        \"invalid_path\": \"❌ Ruta inválida.\\n\\nVe a la carpeta de The Sims 4 y selecciónala.\",\n",
        "        \"no_zip\": \"❌ No seleccionaste ningún archivo .zip.\\n\\nDescarga el archivo y luego selecciónalo.\",\n",
        "        \"invalid_zip\": \"❌ El archivo está corrupto o no es un .zip válido.\\n\\nVuelve a descargarlo.\",\n",
        "        \"success_msg\": \"✓ Contenido instalado correctamente.\",\n",
        "        \"no_path\": \"❌ No seleccionaste la carpeta del juego.\",\n",
        "        \"no_dlc_folder\": \"❌ No seleccionaste la carpeta de DLCs.\\n\\nElige la carpeta donde guardaste los archivos .zip.\",\n",
        "        \"no_zips_found\": \"❌ No se encontraron archivos .zip en esa carpeta.\\n\\nAsegúrate de haber puesto los archivos ahí.\",\n",
        "        \"no_backup_path\": \"❌ No tienes un backup configurado.\\n\\nPrimero selecciona la carpeta de backup.\",\n",
        "        \"backup_empty\": \"❌ La carpeta de backup no contiene archivos .zip.\",\n",
        "        \"installed_msg\": \"✓ {count} DLC(s) instalado(s) correctamente.\",\n",
        "        \"failed_msg\": \"⚠ {count} archivo(s) con error.\",\n",
        "        \"ask_backup_title\": \"¿Crear backup offline?\",\n",
        "        \"ask_backup_msg\": (\n",
        "            \"El contenido se instaló correctamente.\\n\\n\"\n",
        "            \"¿Quieres configurar un backup offline permanente?\\n\\n\"\n",
        "            \"Con esto nunca necesitarás volver a descargar los DLCs. \"\n",
        "            \"Podrás reinstalar todo en cualquier momento, sin internet.\"\n",
        "        ),\n",
        "        \"backup_win_title\": \"Configurar Backup Offline\",\n",
        "        \"backup_what_title\": \"¿Qué es el Backup Offline?\",\n",
        "        \"backup_what_text\": (\n",
        "            \"El Backup Offline es una copia permanente de todos tus DLCs guardada en un lugar \"\n",
        "            \"seguro que TÚ controlas: un disco externo, un USB, Google Drive, etc.\\n\\n\"\n",
        "            \"Una vez configurado, esta aplicación NUNCA más necesitará los enlaces de descarga. \"\n",
        "            \"Todo el proceso será 100% local y offline.\\n\\n\"\n",
        "            \"Solo necesitas descargar los archivos UNA VEZ. Si cuidas bien tu backup, \"\n",
        "            \"tienes los DLCs garantizados para siempre.\"\n",
        "        ),\n",
        "        \"backup_how_title\": \"¿Cómo funciona?\",\n",
        "        \"backup_how_text\": (\n",
        "            \"1.  Guardas todos los archivos .zip que descargaste en una carpeta dedicada \"\n",
        "            \"(disco externo, USB, Google Drive, Dropbox, etc.).\\n\\n\"\n",
        "            \"2.  Le indicas a esta app dónde está esa carpeta.\\n\\n\"\n",
        "            \"3.  La próxima vez que necesites instalar, usas el Modo Offline y la app \"\n",
        "            \"lee directamente de tu backup. Sin internet, sin links, sin esperas.\"\n",
        "        ),\n",
        "        \"backup_storage_title\": \"Espacio necesario\",\n",
        "        \"backup_storage_text\": (\n",
        "            \"Necesitarás aproximadamente 50 GB de espacio libre. Puedes guardarlo en:\\n\\n\"\n",
        "            \"  •  USB de 64 GB o más\\n\"\n",
        "            \"  •  Disco duro o SSD externo\\n\"\n",
        "            \"  •  Google Drive / Dropbox / OneDrive\\n\"\n",
        "            \"  •  Una carpeta en un segundo disco interno\\n\"\n",
        "            \"  •  Cualquier lugar accesible desde este computador\"\n",
        "        ),\n",
        "        \"backup_warning_title\": \"⚠  ADVERTENCIA IMPORTANTE\",\n",
        "        \"backup_warning_text\": (\n",
        "            \"NO pierdas, borres ni muevas la carpeta de backup sin actualizar la app.\\n\\n\"\n",
        "            \"Si pierdes tu USB o disco de backup, tendrás que descargar TODOS los DLCs \"\n",
        "            \"desde cero (~50 GB). Los links de descarga pueden caducar o desaparecer, \"\n",
        "            \"así que tu backup puede ser tu ÚNICA forma de recuperar los archivos.\\n\\n\"\n",
        "            \"Guárdalo en un lugar seguro. Considera tener una copia en 2 lugares distintos.\"\n",
        "        ),\n",
        "        \"backup_setup_title\": \"Selecciona la ubicación del backup\",\n",
        "        \"backup_setup_desc\": (\n",
        "            \"Elige la carpeta donde tienes (o tendrás) todos los archivos .zip. \"\n",
        "            \"Asegúrate de que la carpeta contenga TODOS los archivos antes de continuar.\"\n",
        "        ),\n",
        "        \"backup_current_label\": \"Carpeta seleccionada:\",\n",
        "        \"save_backup\": \"✓  Guardar y activar Modo Offline\",\n",
        "        \"backup_saved_msg\": \"✓ Backup configurado correctamente.\\nYa puedes usar el Modo Offline.\",\n",
        "        \"backup_cancel\": \"Cancelar\",\n",
        "    },\n",
        "    \"en\": {\n",
        "        \"title\": \"The Sims 4 - Content Manager (Original by Leuan)\",\n",
        "        \"language\": \"Language\",\n",
        "        \"select_folder\": \"Select folder\",\n",
        "        \"path_label\": \"Game Path:\",\n",
        "        \"start\": \"Start Installation\",\n",
        "        \"mode_select\": \"Installation Mode\",\n",
        "        \"mode_single\": \"Install single file\",\n",
        "        \"mode_all\": \"Install all DLCs\",\n",
        "        \"mode_offline\": \"Offline Mode (backup)\",\n",
        "        \"step_1\": \"Step 1 — Download the file\",\n",
        "        \"step_1_desc\": \"Click the button below to open the download link and get the .zip file.\",\n",
        "        \"step_2\": \"Step 2 — Select the .zip file\",\n",
        "        \"step_2_desc\": \"Once downloaded, click the button and choose your .zip file.\",\n",
        "        \"step_3\": \"Step 3 — Select the game folder\",\n",
        "        \"step_3_desc\": \"Click the button and choose the folder where The Sims 4 is installed.\",\n",
        "        \"dlc_steps_1\": \"Step 1 — Download all DLCs\",\n",
        "        \"dlc_steps_1_desc\": \"Click the button below to open the download page and get ALL the DLC .zip files.\",\n",
        "        \"dlc_steps_2\": \"Step 2 — Save them in one folder\",\n",
        "        \"dlc_steps_2_desc\": \"Put ALL the downloaded .zip files inside ONE SINGLE FOLDER on your computer.\",\n",
        "        \"dlc_steps_3\": \"Step 3 — Select the DLC folder\",\n",
        "        \"dlc_steps_3_desc\": \"Click the button and choose the folder where you saved all the .zip files.\",\n",
        "        \"dlc_steps_4\": \"Step 4 — Select the game folder\",\n",
        "        \"dlc_steps_4_desc\": \"Click the button and choose the folder where The Sims 4 is installed.\",\n",
        "        \"offline_title\": \"Offline Mode\",\n",
        "        \"offline_desc\": \"Install directly from your local backup. No internet or download links needed.\",\n",
        "        \"offline_step_1\": \"Step 1 — Select your backup folder\",\n",
        "        \"offline_step_1_desc\": \"Choose the folder where you saved all your backup .zip files.\",\n",
        "        \"offline_step_2\": \"Step 2 — Select the game folder\",\n",
        "        \"offline_step_2_desc\": \"Choose the folder where The Sims 4 is installed.\",\n",
        "        \"zip_label\": \"Selected .zip file:\",\n",
        "        \"dlc_folder_label\": \"DLC Folder:\",\n",
        "        \"backup_label\": \"Backup folder:\",\n",
        "        \"zip_ph\": \"No file selected\",\n",
        "        \"path_ph\": \"No path selected\",\n",
        "        \"folder_ph\": \"No folder selected\",\n",
        "        \"backup_ph\": \"Not configured yet\",\n",
        "        \"open_link\": \"🌐  Open download link\",\n",
        "        \"browse_dlcs\": \"📁  Browse DLC Folder\",\n",
        "        \"browse_game\": \"📂  Select game folder\",\n",
        "        \"browse_zip\": \"📄  Select .zip file\",\n",
        "        \"browse_backup\": \"📦  Select backup folder\",\n",
        "        \"install_all\": \"⚙️  Install all DLCs\",\n",
        "        \"install_from_backup\": \"⚙️  Install from Backup\",\n",
        "        \"error\": \"Error\",\n",
        "        \"success\": \"Success\",\n",
        "        \"invalid_path\": \"❌ Invalid path.\\n\\nGo to The Sims 4 folder and select it.\",\n",
        "        \"no_zip\": \"❌ No .zip file selected.\\n\\nDownload the file first, then select it.\",\n",
        "        \"invalid_zip\": \"❌ File is corrupted or not a valid .zip.\\n\\nPlease re-download it.\",\n",
        "        \"success_msg\": \"✓ Content installed successfully.\",\n",
        "        \"no_path\": \"❌ No game folder selected.\",\n",
        "        \"no_dlc_folder\": \"❌ No DLC folder selected.\\n\\nChoose the folder containing your .zip files.\",\n",
        "        \"no_zips_found\": \"❌ No .zip files found in that folder.\\n\\nMake sure you placed the files there.\",\n",
        "        \"no_backup_path\": \"❌ No backup configured.\\n\\nFirst select a backup folder.\",\n",
        "        \"backup_empty\": \"❌ The backup folder contains no .zip files.\",\n",
        "        \"installed_msg\": \"✓ {count} DLC(s) installed successfully.\",\n",
        "        \"failed_msg\": \"⚠ {count} file(s) failed.\",\n",
        "        \"ask_backup_title\": \"Create Offline Backup?\",\n",
        "        \"ask_backup_msg\": (\n",
        "            \"Content installed successfully!\\n\\n\"\n",
        "            \"Would you like to set up a permanent offline backup?\\n\\n\"\n",
        "            \"With this you will NEVER need to download the DLCs again. \"\n",
        "            \"You can reinstall everything at any time, with no internet required.\"\n",
        "        ),\n",
        "        \"backup_win_title\": \"Set Up Offline Backup\",\n",
        "        \"backup_what_title\": \"What is Offline Backup?\",\n",
        "        \"backup_what_text\": (\n",
        "            \"The Offline Backup is a permanent copy of all your DLCs stored in a safe place \"\n",
        "            \"that YOU control: an external drive, USB stick, Google Drive, etc.\\n\\n\"\n",
        "            \"Once configured, this app will NEVER need download links again. \"\n",
        "            \"The entire process becomes 100% local and offline.\\n\\n\"\n",
        "            \"You only need to download the files ONCE. As long as you keep your backup safe, \"\n",
        "            \"your DLCs are guaranteed forever.\"\n",
        "        ),\n",
        "        \"backup_how_title\": \"How does it work?\",\n",
        "        \"backup_how_text\": (\n",
        "            \"1.  You save all the .zip files you downloaded into a dedicated folder \"\n",
        "            \"(external drive, USB stick, Google Drive, Dropbox, etc.).\\n\\n\"\n",
        "            \"2.  You tell this app where that folder is.\\n\\n\"\n",
        "            \"3.  Next time you need to install, use Offline Mode and the app reads \"\n",
        "            \"directly from your backup. No internet, no links, no waiting.\"\n",
        "        ),\n",
        "        \"backup_storage_title\": \"Storage Requirements\",\n",
        "        \"backup_storage_text\": (\n",
        "            \"You will need approximately 50 GB of free space. You can store it on:\\n\\n\"\n",
        "            \"  •  USB stick (64 GB or larger)\\n\"\n",
        "            \"  •  External hard drive or SSD\\n\"\n",
        "            \"  •  Google Drive / Dropbox / OneDrive\\n\"\n",
        "            \"  •  A folder on a second internal drive\\n\"\n",
        "            \"  •  Any location accessible from this computer\"\n",
        "        ),\n",
        "        \"backup_warning_title\": \"⚠  IMPORTANT WARNING\",\n",
        "        \"backup_warning_text\": (\n",
        "            \"Do NOT lose, delete, or move the backup folder without updating this app.\\n\\n\"\n",
        "            \"If you lose your USB drive or backup folder, you will have to re-download \"\n",
        "            \"ALL DLCs from scratch (~50 GB). Download links may expire or disappear over time, \"\n",
        "            \"making your backup your ONLY way to recover the files.\\n\\n\"\n",
        "            \"Keep it somewhere safe. Consider keeping a copy in 2 different locations.\"\n",
        "        ),\n",
        "        \"backup_setup_title\": \"Select backup location\",\n",
        "        \"backup_setup_desc\": (\n",
        "            \"Choose the folder where you have (or will have) all the .zip files saved. \"\n",
        "            \"Make sure the folder contains ALL the files before continuing.\"\n",
        "        ),\n",
        "        \"backup_current_label\": \"Selected folder:\",\n",
        "        \"save_backup\": \"✓  Save & Enable Offline Mode\",\n",
        "        \"backup_saved_msg\": \"✓ Backup configured.\\nYou can now use Offline Mode anytime.\",\n",
        "        \"backup_cancel\": \"Cancel\",\n",
        "    },\n",
        "}\n",
        "\n",
        "SIMS4_DLCS = [\n",
        "    \"Life of the Party Digital Content\", \"Up All Night Digital Content\",\n",
        "    \"Digital Deluxe Upgrade\", \"The Sims™ 4 Holiday Celebration Pack\",\n",
        "    \"The Sims™ 4 Outdoor Retreat\", \"The Sims™ 4 Get to Work\",\n",
        "    \"The Sims™ 4 Luxury Party Stuff\", \"The Sims™ 4 Perfect Patio Stuff\",\n",
        "    \"The Sims™ 4 Spa Day\", \"The Sims™ 4 Cool Kitchen Stuff\",\n",
        "    \"The Sims™ 4 Spooky Stuff\", \"The Sims™ 4 Get Together\",\n",
        "    \"The Sims™ 4 Movie Hangout Stuff\", \"The Sims™ 4 Romantic Garden Stuff\",\n",
        "    \"The Sims™ 4 Dine Out\", \"The Sims™ 4 Kids Room Stuff\",\n",
        "    \"The Sims™ 4 Backyard Stuff\", \"The Sims™ 4 City Living\",\n",
        "    \"The Sims™ 4 Vintage Glamour Stuff\", \"The Sims™ 4 Vampires\",\n",
        "    \"The Sims™ 4 Bowling Night Stuff\", \"The Sims™ 4 Parenthood\",\n",
        "    \"The Sims™ 4 Fitness Stuff\", \"The Sims™ 4 Toddler Stuff\",\n",
        "    \"The Sims™ 4 Cats & Dogs\", \"The Sims™ 4 Laundry Day Stuff\",\n",
        "    \"The Sims™ 4 Jungle Adventure\", \"The Sims™ 4 My First Pet Stuff\",\n",
        "    \"The Sims™ 4 Seasons\", \"The Sims™ 4 Get Famous\",\n",
        "    \"The Sims™ 4 StrangerVille\", \"The Sims™ 4 Island Living\",\n",
        "    \"The Sims™ 4 Moschino Stuff Pack\", \"The Sims™ 4 Realm of Magic\",\n",
        "    \"The Sims™ 4 Discover University\", \"The Sims™ 4 Tiny Living\",\n",
        "    \"The Sims™ 4 Eco Lifestyle\", \"The Sims™ 4 Nifty Knitting Stuff Pack\",\n",
        "    \"The Sims™ 4 STAR WARS™: Journey to Batuu Game Pack\", \"The Sims™ 4 Snowy Escape\",\n",
        "    \"The Sims™ 4 Paranormal Stuff Pack\", \"The Sims™ 4 Throwback Fit Kit\",\n",
        "    \"The Sims™ 4 Country Kitchen Kit\", \"The Sims™ 4 Bust the Dust Kit\",\n",
        "    \"The Sims™ 4 Courtyard Oasis Kit\", \"The Sims™ 4 Dream Home Decorator\",\n",
        "    \"The Sims™ 4 Cottage Living\", \"The Sims™ 4 Industrial Loft Kit\",\n",
        "    \"The Sims™ 4 Fashion Street Kit\", \"The Sims™ 4 Incheon Arrivals Kit\",\n",
        "    \"The Sims™ 4 Blooming Rooms Kit\", \"The Sims™ 4 Modern Menswear Kit\",\n",
        "    \"The Sims™ 4 Carnaval Streetwear Kit\", \"The Sims™ 4 My Wedding Stories\",\n",
        "    \"The Sims™ 4 Décor to the Max Kit\", \"The Sims™ 4 Moonlight Chic Kit\",\n",
        "    \"The Sims™ 4 Little Campers Kit\", \"The Sims™ 4 Werewolves\",\n",
        "    \"The Sims™ 4 High School Years\", \"The Sims™ 4 First Fits Kit\",\n",
        "    \"The Sims™ 4 Desert Luxe Kit\", \"The Sims™ 4 Pastel Pop Kit\",\n",
        "    \"The Sims™ 4 Everyday Clutter Kit\", \"The Sims™ 4 Simtimates Collection Kit\",\n",
        "    \"The Sims™ 4 Bathroom Clutter Kit\", \"The Sims™ 4 Growing Together\",\n",
        "    \"The Sims™ 4 Greenhouse Haven Kit\", \"The Sims™ 4 Basement Treasures Kit\",\n",
        "    \"The Sims™ 4 Grunge Revival Kit\", \"The Sims™ 4 Book Nook Kit\",\n",
        "    \"The Sims™ 4 Horse Ranch\", \"The Sims™ 4 Poolside Splash Kit\",\n",
        "    \"The Sims™ 4 Modern Luxe Kit\", \"The Sims™ 4 Home Chef Hustle Stuff Pack\",\n",
        "    \"The Sims™ 4 For Rent\", \"The Sims™ 4 Castle Estate Kit\",\n",
        "    \"The Sims™ 4 Goth Galore Kit\", \"The Sims™ 4 Crystal Creations Stuff Pack\",\n",
        "    \"The Sims™ 4 Urban Homage Kit\", \"The Sims™ 4 Party Essentials Kit\",\n",
        "    \"The Sims™ 4 Riviera Retreat Kit\", \"The Sims™ 4 Cozy Bistro Kit\",\n",
        "    \"The Sims™ 4 Lovestruck\", \"The Sims™ 4 Artist Studio Kit\",\n",
        "    \"The Sims™ 4 Storybook Nursery Kit\", \"The Sims™ 4 Life & Death\",\n",
        "    \"The Sims™ 4 Sweet Slumber Party Kit\", \"The Sims™ 4 Cozy Kitsch Kit\",\n",
        "    \"The Sims™ 4 Comfy Gamer Kit\", \"The Sims™ 4 Secret Sanctuary Kit\",\n",
        "    \"The Sims™ 4 Casanova Cave Kit\", \"The Sims™ 4 Refined Living Room Kit\",\n",
        "    \"The Sims™ 4 Business Chic Kit\", \"The Sims™ 4 Businesses & Hobbies\",\n",
        "    \"The Sims™ 4 Sleek Bathroom Kit\", \"The Sims™ 4 Sweet Allure Kit\",\n",
        "    \"The Sims™ 4 Restoration Workshop Kit\", \"The Sims™ 4 Kitchen Clutter Kit\",\n",
        "    \"The Sims™ 4 Golden Years Kit\", \"The Sims™ 4 Enchanted by Nature Expansion Pack\",\n",
        "    \"The Sims™ 4 Essential Glam Kit\", \"The Sims™ 4 Grange Mudroom Kit\",\n",
        "    \"The Sims™ 4 Adventure Awaits Expansion Pack\", \"The Sims™ 4 Autumn Apparel Kit\",\n",
        "    \"The Sims™ 4 Modern Retreat Kit\", \"The Sims™ 4 Garden to Table Kit\",\n",
        "    \"The Sims™ 4 SpongeBob's House Kit\", \"The Sims™ 4 SpongeBob Kid's Room Kit\",\n",
        "    \"The Sims™ 4 Prairie Dreams Kit\", \"The Sims™ 4 Royalty & Legacy Grand Bundle\",\n",
        "    \"The Sims™ 4 Silver Screen Style Kit\", \"The Sims™ 4 Tea Time Solarium Kit\",\n",
        "    \"The Sims™ 4 Wonderland Playroom Kit\", \"The Sims™ 4 Yard Charm (Creator) Kit\",\n",
        "    \"Readers Nook\", \"The Sims™ 4 Lady Bridgerton's Masquerade Ballroom Kit\",\n",
        "    \"The Sims™ 4 Lady Bridgerton's Masquerade Ball Fashion Kit\",\n",
        "]\n",
        "\n",
        "\n",
        "# ==================== APP ====================\n",
        "class App:\n",
        "    def __init__(self, root):\n",
        "        self.root = root\n",
        "        self.lang = \"en\"\n",
        "        self.mode = \"single\"\n",
        "        self.zip_path = None\n",
        "        self.game_path = None\n",
        "        self.dlc_folder = None\n",
        "        self.backup_path = None\n",
        "\n",
        "        self.lang_var = tk.StringVar(value=\"en\")\n",
        "        self.mode_var = tk.StringVar(value=\"single\")\n",
        "\n",
        "        self._load_config()\n",
        "        self._setup_window()\n",
        "        self._setup_styles()\n",
        "        self._setup_scroll()\n",
        "        self._build()\n",
        "\n",
        "    # ── Config ──────────────────────────────────────────────────────\n",
        "    def _load_config(self):\n",
        "        try:\n",
        "            with open(CONFIG_FILE, encoding=\"utf-8\") as f:\n",
        "                self.backup_path = json.load(f).get(\"backup_path\")\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    def _save_config(self):\n",
        "        try:\n",
        "            with open(CONFIG_FILE, \"w\", encoding=\"utf-8\") as f:\n",
        "                json.dump({\"backup_path\": self.backup_path}, f, ensure_ascii=False)\n",
        "        except Exception:\n",
        "            pass\n",
        "\n",
        "    # ── Window ──────────────────────────────────────────────────────\n",
        "    def _setup_window(self):\n",
        "        sw = self.root.winfo_screenwidth()\n",
        "        sh = self.root.winfo_screenheight()\n",
        "        w = max(min(int(sw * 0.52), 960), 720)\n",
        "        h = max(min(int(sh * 0.80), 820), 560)\n",
        "        x = (sw - w) // 2\n",
        "        y = (sh - h) // 2\n",
        "        self.root.geometry(f\"{w}x{h}+{x}+{y}\")\n",
        "        self.root.minsize(580, 500)\n",
        "        self.root.title(T[self.lang][\"title\"])\n",
        "        self.root.configure(bg=C[\"bg\"])\n",
        "\n",
        "    # ── Styles ──────────────────────────────────────────────────────\n",
        "    def _setup_styles(self):\n",
        "        s = ttk.Style()\n",
        "        s.theme_use(\"clam\")\n",
        "        s.configure(\"TFrame\",      background=C[\"bg\"])\n",
        "        s.configure(\"Card.TFrame\", background=C[\"card\"])\n",
        "        s.configure(\"TLabel\",      background=C[\"bg\"], foreground=C[\"fg\"], font=(FONT, 10))\n",
        "        s.configure(\"TRadiobutton\",background=C[\"bg\"], foreground=C[\"fg\"], font=(FONT, 10))\n",
        "        s.configure(\"TScrollbar\",  background=C[\"card\"], troughcolor=C[\"bg\"], borderwidth=0)\n",
        "        s.configure(\"TButton\",\n",
        "                    background=C[\"card\"], foreground=C[\"fg\"],\n",
        "                    font=(FONT, 10), padding=(12, 9), borderwidth=1,\n",
        "                    relief=\"flat\")\n",
        "        s.map(\"TButton\",\n",
        "              background=[(\"active\", C[\"accent\"])],\n",
        "              foreground=[(\"active\", \"#ffffff\")])\n",
        "        s.configure(\"Accent.TButton\",\n",
        "                    background=C[\"accent\"], foreground=\"#ffffff\",\n",
        "                    font=(FONT, 11, \"bold\"), padding=(12, 11))\n",
        "        s.map(\"Accent.TButton\",\n",
        "              background=[(\"active\", C[\"accent_h\"])])\n",
        "\n",
        "    # ── Scroll area ─────────────────────────────────────────────────\n",
        "    def _setup_scroll(self):\n",
        "        self._canvas = tk.Canvas(self.root, bg=C[\"bg\"], highlightthickness=0)\n",
        "        self._sb = ttk.Scrollbar(self.root, orient=\"vertical\", command=self._canvas.yview)\n",
        "        self._canvas.configure(yscrollcommand=self._sb.set)\n",
        "\n",
        "        # inner page — plain tk.Frame so bg works correctly\n",
        "        self._page = tk.Frame(self._canvas, bg=C[\"bg\"])\n",
        "        self._win_id = self._canvas.create_window((0, 0), window=self._page, anchor=\"nw\")\n",
        "\n",
        "        # keep inner frame width == canvas width\n",
        "        self._canvas.bind(\"<Configure>\",\n",
        "                          lambda e: self._canvas.itemconfigure(self._win_id, width=e.width))\n",
        "        # update scroll region when content grows/shrinks\n",
        "        self._page.bind(\"<Configure>\",\n",
        "                        lambda *_: self._canvas.configure(scrollregion=self._canvas.bbox(\"all\")))\n",
        "\n",
        "        # mousewheel — cross-platform\n",
        "        def _scroll(e):\n",
        "            if _SYS == \"Darwin\":\n",
        "                self._canvas.yview_scroll(-1 * int(e.delta), \"units\")\n",
        "            elif _SYS == \"Windows\":\n",
        "                self._canvas.yview_scroll(-1 * int(e.delta / 120), \"units\")\n",
        "            else:\n",
        "                self._canvas.yview_scroll(-1 if e.num == 4 else 1, \"units\")\n",
        "\n",
        "        if _SYS in (\"Windows\", \"Darwin\"):\n",
        "            self._canvas.bind_all(\"<MouseWheel>\", _scroll)\n",
        "        else:\n",
        "            self._canvas.bind_all(\"<Button-4>\", _scroll)\n",
        "            self._canvas.bind_all(\"<Button-5>\", _scroll)\n",
        "\n",
        "        self._sb.pack(side=tk.RIGHT, fill=tk.Y)\n",
        "        self._canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)\n",
        "\n",
        "    # ── Rebuild ──────────────────────────────────────────────────────\n",
        "    def _rebuild(self):\n",
        "        for w in self._page.winfo_children():\n",
        "            w.destroy()\n",
        "        self._canvas.yview_moveto(0)\n",
        "        self._build()\n",
        "\n",
        "    # ── Primitive widgets ─────────────────────────────────────────────\n",
        "    def t(self, k):\n",
        "        return T[self.lang][k]\n",
        "\n",
        "    def _label(self, text, fg=None, size=10, bold=False, pady=(0, 0)):\n",
        "        \"\"\"Single-line label, left-aligned.\"\"\"\n",
        "        font = (FONT, size, \"bold\") if bold else (FONT, size)\n",
        "        lbl = tk.Label(self._page, text=text, bg=C[\"bg\"],\n",
        "                       fg=fg or C[\"fg\"], font=font, anchor=\"w\")\n",
        "        lbl.pack(fill=tk.X, padx=PAD, pady=pady)\n",
        "        return lbl\n",
        "\n",
        "    def _desc(self, text, pady=(0, 14)):\n",
        "        \"\"\"Multi-line description that wraps to available width.\"\"\"\n",
        "        lbl = tk.Label(self._page, text=text, bg=C[\"bg\"], fg=C[\"desc\"],\n",
        "                       font=(FONT, 10), justify=tk.LEFT, anchor=\"nw\")\n",
        "        lbl.pack(fill=tk.X, padx=PAD + 4, pady=pady)\n",
        "        lbl.bind(\"<Configure>\",\n",
        "                 lambda e, l=lbl: l.configure(wraplength=max(100, e.width - 2)))\n",
        "        return lbl\n",
        "\n",
        "    def _section(self, title):\n",
        "        \"\"\"Bold section heading + underline.\"\"\"\n",
        "        tk.Label(self._page, text=title, bg=C[\"bg\"], fg=C[\"fg\"],\n",
        "                 font=(FONT, 11, \"bold\"), anchor=\"w\").pack(\n",
        "            fill=tk.X, padx=PAD, pady=(20, 4))\n",
        "        tk.Frame(self._page, height=1, bg=C[\"border\"]).pack(\n",
        "            fill=tk.X, padx=PAD, pady=(0, 8))\n",
        "\n",
        "    def _divider(self):\n",
        "        tk.Frame(self._page, height=1, bg=C[\"border\"]).pack(\n",
        "            fill=tk.X, padx=PAD, pady=16)\n",
        "\n",
        "    def _btn(self, text, cmd, accent=False, pady=(0, 8)):\n",
        "        style = \"Accent.TButton\" if accent else \"TButton\"\n",
        "        ttk.Button(self._page, text=text, command=cmd, style=style).pack(\n",
        "            fill=tk.X, padx=PAD, pady=pady)\n",
        "\n",
        "    def _path_box(self, placeholder, pady=(0, 8)):\n",
        "        \"\"\"Displays a selected path; returns the label so caller can update it.\"\"\"\n",
        "        lbl = tk.Label(self._page, text=placeholder,\n",
        "                       bg=C[\"card\"], fg=C[\"muted\"],\n",
        "                       font=(FONT, 9), anchor=\"w\",\n",
        "                       padx=12, pady=10)\n",
        "        lbl.pack(fill=tk.X, padx=PAD, pady=pady)\n",
        "        lbl.bind(\"<Configure>\",\n",
        "                 lambda e, l=lbl: l.configure(wraplength=max(100, e.width - 24)))\n",
        "        return lbl\n",
        "\n",
        "    # ── Main build ────────────────────────────────────────────────────\n",
        "    def _build(self):\n",
        "        p = self._page\n",
        "\n",
        "        # ── Header ──\n",
        "        tk.Label(p, text=\"The Sims 4\", bg=C[\"bg\"], fg=C[\"accent\"],\n",
        "                 font=(FONT, 22, \"bold\")).pack(pady=(28, 2))\n",
        "        tk.Label(p, text=\"Source Code by Leuan. Translations by Leuan. Modified by thelinuxsimmer/Melon The Goblin. Made for KristinaPlaysTheSims\", bg=C[\"bg\"], fg=C[\"muted\"],\n",
        "                 font=(FONT, 11)).pack(pady=(0, 20))\n",
        "\n",
        "        # ── Language ──\n",
        "        row = tk.Frame(p, bg=C[\"bg\"])\n",
        "        row.pack(fill=tk.X, padx=PAD, pady=(0, 4))\n",
        "        tk.Label(row, text=self.t(\"language\") + \":\", bg=C[\"bg\"], fg=C[\"fg\"],\n",
        "                 font=(FONT, 10, \"bold\")).pack(side=tk.LEFT)\n",
        "        ttk.Radiobutton(row, text=\"English\", variable=self.lang_var, value=\"en\",\n",
        "                        command=lambda: self._set_lang(\"en\")).pack(side=tk.LEFT, padx=(16, 0))\n",
        "        ttk.Radiobutton(row, text=\"Español\", variable=self.lang_var, value=\"es\",\n",
        "                        command=lambda: self._set_lang(\"es\")).pack(side=tk.LEFT, padx=(10, 0))\n",
        "\n",
        "        self._divider()\n",
        "\n",
        "        # ── Mode selector ──\n",
        "        tk.Label(p, text=self.t(\"mode_select\"), bg=C[\"bg\"], fg=C[\"fg\"],\n",
        "                 font=(FONT, 11, \"bold\")).pack(fill=tk.X, padx=PAD, pady=(0, 10))\n",
        "\n",
        "        modes = [\n",
        "            (\"single\",  \"▶   \" + self.t(\"mode_single\")),\n",
        "            (\"all\",     \"📦  \" + self.t(\"mode_all\")),\n",
        "            (\"offline\", \"💾  \" + self.t(\"mode_offline\")),\n",
        "        ]\n",
        "        for val, label in modes:\n",
        "            ttk.Radiobutton(p, text=label, variable=self.mode_var, value=val,\n",
        "                            command=lambda v=val: self._set_mode(v)).pack(\n",
        "                anchor=tk.W, padx=PAD + 8, pady=3)\n",
        "\n",
        "        self._divider()\n",
        "\n",
        "        # ── Mode content ──\n",
        "        if self.mode == \"all\":\n",
        "            self._build_all()\n",
        "        elif self.mode == \"offline\":\n",
        "            self._build_offline()\n",
        "        else:\n",
        "            self._build_single()\n",
        "\n",
        "        # bottom breathing room\n",
        "        tk.Frame(p, bg=C[\"bg\"], height=32).pack()\n",
        "\n",
        "    # ── Single file ───────────────────────────────────────────────────\n",
        "    def _build_single(self):\n",
        "        self._section(self.t(\"step_1\"))\n",
        "        self._desc(self.t(\"step_1_desc\"))\n",
        "        self._btn(self.t(\"open_link\"), self._open_link)\n",
        "\n",
        "        self._section(self.t(\"step_2\"))\n",
        "        self._desc(self.t(\"step_2_desc\"))\n",
        "        self._label(self.t(\"zip_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.zip_lbl = self._path_box(self.t(\"zip_ph\"))\n",
        "        if self.zip_path:\n",
        "            self.zip_lbl.config(text=f\"✓  {self.zip_path}\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_zip\"), self._pick_zip)\n",
        "\n",
        "        self._section(self.t(\"step_3\"))\n",
        "        self._desc(self.t(\"step_3_desc\"))\n",
        "        self._label(self.t(\"path_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.game_lbl = self._path_box(self.t(\"path_ph\"))\n",
        "        if self.game_path:\n",
        "            self.game_lbl.config(text=f\"✓  {self.game_path}\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_game\"), self._pick_game_single)\n",
        "\n",
        "        self._divider()\n",
        "        self._btn(\"▶   \" + self.t(\"start\"), self._install_single, accent=True, pady=(0, 0))\n",
        "\n",
        "    # ── All DLCs ──────────────────────────────────────────────────────\n",
        "    def _build_all(self):\n",
        "        self._section(self.t(\"dlc_steps_1\"))\n",
        "        self._desc(self.t(\"dlc_steps_1_desc\"))\n",
        "        self._btn(self.t(\"open_link\"), self._open_link)\n",
        "\n",
        "        self._section(self.t(\"dlc_steps_2\"))\n",
        "        self._desc(self.t(\"dlc_steps_2_desc\"))\n",
        "\n",
        "        self._section(self.t(\"dlc_steps_3\"))\n",
        "        self._desc(self.t(\"dlc_steps_3_desc\"))\n",
        "        self._label(self.t(\"dlc_folder_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.dlc_lbl = self._path_box(self.t(\"folder_ph\"))\n",
        "        if self.dlc_folder:\n",
        "            n = sum(1 for f in os.listdir(self.dlc_folder) if f.endswith(\".zip\"))\n",
        "            self.dlc_lbl.config(text=f\"✓  {self.dlc_folder}  ({n} .zip files)\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_dlcs\"), self._pick_dlc_folder)\n",
        "\n",
        "        self._section(self.t(\"dlc_steps_4\"))\n",
        "        self._desc(self.t(\"dlc_steps_4_desc\"))\n",
        "        self._label(self.t(\"path_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.game_lbl2 = self._path_box(self.t(\"path_ph\"))\n",
        "        if self.game_path:\n",
        "            self.game_lbl2.config(text=f\"✓  {self.game_path}\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_game\"), self._pick_game_all)\n",
        "\n",
        "        self._divider()\n",
        "        self._btn(self.t(\"install_all\"), self._install_all, accent=True, pady=(0, 0))\n",
        "\n",
        "    # ── Offline ───────────────────────────────────────────────────────\n",
        "    def _build_offline(self):\n",
        "        self._section(self.t(\"offline_title\"))\n",
        "        self._desc(self.t(\"offline_desc\"))\n",
        "\n",
        "        self._section(self.t(\"offline_step_1\"))\n",
        "        self._desc(self.t(\"offline_step_1_desc\"))\n",
        "        self._label(self.t(\"backup_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.bk_lbl = self._path_box(self.t(\"backup_ph\"))\n",
        "        if self.backup_path and os.path.isdir(self.backup_path):\n",
        "            n = sum(1 for f in os.listdir(self.backup_path) if f.endswith(\".zip\"))\n",
        "            self.bk_lbl.config(text=f\"✓  {self.backup_path}  ({n} .zip files)\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_backup\"), self._pick_backup)\n",
        "\n",
        "        self._section(self.t(\"offline_step_2\"))\n",
        "        self._desc(self.t(\"offline_step_2_desc\"))\n",
        "        self._label(self.t(\"path_label\"), fg=C[\"muted\"], size=9, pady=(0, 4))\n",
        "        self.game_lbl3 = self._path_box(self.t(\"path_ph\"))\n",
        "        if self.game_path:\n",
        "            self.game_lbl3.config(text=f\"✓  {self.game_path}\", fg=C[\"success\"])\n",
        "        self._btn(self.t(\"browse_game\"), self._pick_game_offline)\n",
        "\n",
        "        self._divider()\n",
        "        self._btn(self.t(\"install_from_backup\"), self._install_offline, accent=True, pady=(0, 0))\n",
        "\n",
        "    # ── Language / mode ───────────────────────────────────────────────\n",
        "    def _set_lang(self, lang):\n",
        "        self.lang = lang\n",
        "        self.root.title(T[lang][\"title\"])\n",
        "        self._rebuild()\n",
        "\n",
        "    def _set_mode(self, mode):\n",
        "        self.mode = mode\n",
        "        self._rebuild()\n",
        "\n",
        "    # ── Browse actions ────────────────────────────────────────────────\n",
        "    def _pick_zip(self):\n",
        "        p = filedialog.askopenfilename(filetypes=[(\"ZIP\", \"*.zip\"), (\"All\", \"*.*\")])\n",
        "        if p:\n",
        "            self.zip_path = p\n",
        "            self.zip_lbl.config(text=f\"✓  {p}\", fg=C[\"success\"])\n",
        "\n",
        "    def _pick_game_single(self):\n",
        "        p = filedialog.askdirectory()\n",
        "        if p:\n",
        "            self.game_path = p\n",
        "            self.game_lbl.config(text=f\"✓  {p}\", fg=C[\"success\"])\n",
        "\n",
        "    def _pick_game_all(self):\n",
        "        p = filedialog.askdirectory()\n",
        "        if p:\n",
        "            self.game_path = p\n",
        "            self.game_lbl2.config(text=f\"✓  {p}\", fg=C[\"success\"])\n",
        "\n",
        "    def _pick_game_offline(self):\n",
        "        p = filedialog.askdirectory()\n",
        "        if p:\n",
        "            self.game_path = p\n",
        "            self.game_lbl3.config(text=f\"✓  {p}\", fg=C[\"success\"])\n",
        "\n",
        "    def _pick_dlc_folder(self):\n",
        "        p = filedialog.askdirectory()\n",
        "        if p:\n",
        "            self.dlc_folder = p\n",
        "            n = sum(1 for f in os.listdir(p) if f.endswith(\".zip\"))\n",
        "            color = C[\"success\"] if n else C[\"error\"]\n",
        "            self.dlc_lbl.config(\n",
        "                text=f\"{'✓' if n else '⚠'}  {p}  ({n} .zip files found)\", fg=color)\n",
        "\n",
        "    def _pick_backup(self):\n",
        "        p = filedialog.askdirectory()\n",
        "        if p:\n",
        "            self.backup_path = p\n",
        "            self._save_config()\n",
        "            n = sum(1 for f in os.listdir(p) if f.endswith(\".zip\"))\n",
        "            color = C[\"success\"] if n else C[\"warning\"]\n",
        "            self.bk_lbl.config(\n",
        "                text=f\"✓  {p}  ({n} .zip files)\", fg=color)\n",
        "\n",
        "    def _open_link(self):\n",
        "        webbrowser.open(KRISTINA_MEDIAFIRE)\n",
        "        webbrowser.open(YOUTUBE_LINK)\n",
        "        webbrowser.open(LEUANS_SERVER)\n",
        "        webbrowser.open(MELON_ARCHIVE)\n",
        "\n",
        "    # ── Error helper ──────────────────────────────────────────────────\n",
        "    def _err(self, key):\n",
        "        messagebox.showerror(self.t(\"error\"), self.t(key))\n",
        "\n",
        "    # ── Install ───────────────────────────────────────────────────────\n",
        "    def _install_single(self):\n",
        "        if not self.zip_path:\n",
        "            return self._err(\"no_zip\")\n",
        "        if not self.game_path or not os.path.isdir(self.game_path):\n",
        "            return self._err(\"no_path\" if not self.game_path else \"invalid_path\")\n",
        "        if not zipfile.is_zipfile(self.zip_path):\n",
        "            return self._err(\"invalid_zip\")\n",
        "        try:\n",
        "            with zipfile.ZipFile(self.zip_path) as zf:\n",
        "                zf.extractall(self.game_path)\n",
        "            messagebox.showinfo(self.t(\"success\"), self.t(\"success_msg\"))\n",
        "            self._offer_backup()\n",
        "        except Exception as e:\n",
        "            messagebox.showerror(self.t(\"error\"), str(e))\n",
        "\n",
        "    def _install_all(self):\n",
        "        if not self.dlc_folder:\n",
        "            return self._err(\"no_dlc_folder\")\n",
        "        if not self.game_path or not os.path.isdir(self.game_path):\n",
        "            return self._err(\"no_path\" if not self.game_path else \"invalid_path\")\n",
        "        zips = [f for f in os.listdir(self.dlc_folder) if f.endswith(\".zip\")]\n",
        "        if not zips:\n",
        "            return self._err(\"no_zips_found\")\n",
        "        ok = fail = 0\n",
        "        for name in zips:\n",
        "            fp = os.path.join(self.dlc_folder, name)\n",
        "            try:\n",
        "                if zipfile.is_zipfile(fp):\n",
        "                    with zipfile.ZipFile(fp) as zf:\n",
        "                        zf.extractall(self.game_path)\n",
        "                    ok += 1\n",
        "                else:\n",
        "                    fail += 1\n",
        "            except Exception:\n",
        "                fail += 1\n",
        "        msg = self.t(\"installed_msg\").format(count=ok)\n",
        "        if fail:\n",
        "            msg += \"\\n\" + self.t(\"failed_msg\").format(count=fail)\n",
        "        messagebox.showinfo(self.t(\"success\"), msg)\n",
        "        self._offer_backup()\n",
        "\n",
        "    def _install_offline(self):\n",
        "        if not self.backup_path or not os.path.isdir(self.backup_path):\n",
        "            return self._err(\"no_backup_path\")\n",
        "        if not self.game_path or not os.path.isdir(self.game_path):\n",
        "            return self._err(\"no_path\" if not self.game_path else \"invalid_path\")\n",
        "        zips = [f for f in os.listdir(self.backup_path) if f.endswith(\".zip\")]\n",
        "        if not zips:\n",
        "            return self._err(\"backup_empty\")\n",
        "        ok = fail = 0\n",
        "        for name in zips:\n",
        "            fp = os.path.join(self.backup_path, name)\n",
        "            try:\n",
        "                if zipfile.is_zipfile(fp):\n",
        "                    with zipfile.ZipFile(fp) as zf:\n",
        "                        zf.extractall(self.game_path)\n",
        "                    ok += 1\n",
        "                else:\n",
        "                    fail += 1\n",
        "            except Exception:\n",
        "                fail += 1\n",
        "        msg = self.t(\"installed_msg\").format(count=ok)\n",
        "        if fail:\n",
        "            msg += \"\\n\" + self.t(\"failed_msg\").format(count=fail)\n",
        "        messagebox.showinfo(self.t(\"success\"), msg)\n",
        "\n",
        "    # ── Offline backup offer ──────────────────────────────────────────\n",
        "    def _offer_backup(self):\n",
        "        if self.backup_path and os.path.isdir(self.backup_path):\n",
        "            return\n",
        "        if messagebox.askyesno(self.t(\"ask_backup_title\"), self.t(\"ask_backup_msg\")):\n",
        "            self._backup_window()\n",
        "\n",
        "    # ── Backup setup window ───────────────────────────────────────────\n",
        "    def _backup_window(self):\n",
        "        win = tk.Toplevel(self.root)\n",
        "        win.title(self.t(\"backup_win_title\"))\n",
        "        sw = win.winfo_screenwidth()\n",
        "        sh = win.winfo_screenheight()\n",
        "        w = max(min(int(sw * 0.48), 860), 620)\n",
        "        h = max(min(int(sh * 0.78), 760), 520)\n",
        "        win.geometry(f\"{w}x{h}+{(sw-w)//2}+{(sh-h)//2}\")\n",
        "        win.minsize(520, 460)\n",
        "        win.configure(bg=C[\"bg\"])\n",
        "        win.grab_set()\n",
        "\n",
        "        # Canvas + scrollbar\n",
        "        canvas = tk.Canvas(win, bg=C[\"bg\"], highlightthickness=0)\n",
        "        sb = ttk.Scrollbar(win, orient=\"vertical\", command=canvas.yview)\n",
        "        canvas.configure(yscrollcommand=sb.set)\n",
        "        page = tk.Frame(canvas, bg=C[\"bg\"])\n",
        "        wid = canvas.create_window((0, 0), window=page, anchor=\"nw\")\n",
        "        canvas.bind(\"<Configure>\", lambda e: canvas.itemconfigure(wid, width=e.width))\n",
        "        page.bind(\"<Configure>\",   lambda *_: canvas.configure(scrollregion=canvas.bbox(\"all\")))\n",
        "        sb.pack(side=tk.RIGHT, fill=tk.Y)\n",
        "        canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)\n",
        "\n",
        "        BP = 28  # backup window padding\n",
        "\n",
        "        def heading(text):\n",
        "            tk.Label(page, text=text, bg=C[\"bg\"], fg=C[\"fg\"],\n",
        "                     font=(FONT, 11, \"bold\"), anchor=\"w\").pack(\n",
        "                fill=tk.X, padx=BP, pady=(20, 4))\n",
        "            tk.Frame(page, height=1, bg=C[\"border\"]).pack(fill=tk.X, padx=BP, pady=(0, 8))\n",
        "\n",
        "        def body(text, fg=None):\n",
        "            lbl = tk.Label(page, text=text, bg=C[\"bg\"], fg=fg or C[\"desc\"],\n",
        "                           font=(FONT, 10), justify=tk.LEFT, anchor=\"nw\")\n",
        "            lbl.pack(fill=tk.X, padx=BP + 4, pady=(0, 10))\n",
        "            lbl.bind(\"<Configure>\", lambda e, l=lbl: l.configure(wraplength=max(100, e.width - 2)))\n",
        "\n",
        "        # Title\n",
        "        tk.Label(page, text=\"📦  \" + self.t(\"backup_win_title\"),\n",
        "                 bg=C[\"bg\"], fg=C[\"accent\"],\n",
        "                 font=(FONT, 18, \"bold\")).pack(pady=(28, 4))\n",
        "        tk.Frame(page, height=2, bg=C[\"accent\"]).pack(fill=tk.X, padx=BP, pady=(0, 6))\n",
        "\n",
        "        heading(self.t(\"backup_what_title\"))\n",
        "        body(self.t(\"backup_what_text\"))\n",
        "\n",
        "        heading(self.t(\"backup_how_title\"))\n",
        "        body(self.t(\"backup_how_text\"))\n",
        "\n",
        "        heading(self.t(\"backup_storage_title\"))\n",
        "        body(self.t(\"backup_storage_text\"))\n",
        "\n",
        "        # Warning card\n",
        "        card = tk.Frame(page, bg=\"#1e1200\", bd=0)\n",
        "        card.pack(fill=tk.X, padx=BP, pady=(16, 6))\n",
        "        tk.Label(card, text=self.t(\"backup_warning_title\"),\n",
        "                 bg=\"#1e1200\", fg=C[\"warning\"],\n",
        "                 font=(FONT, 10, \"bold\"), anchor=\"w\").pack(\n",
        "            fill=tk.X, padx=14, pady=(12, 4))\n",
        "        wlbl = tk.Label(card, text=self.t(\"backup_warning_text\"),\n",
        "                        bg=\"#1e1200\", fg=\"#e0c080\",\n",
        "                        font=(FONT, 10), justify=tk.LEFT, anchor=\"nw\")\n",
        "        wlbl.pack(fill=tk.X, padx=18, pady=(0, 14))\n",
        "        wlbl.bind(\"<Configure>\", lambda e, l=wlbl: l.configure(wraplength=max(100, e.width - 2)))\n",
        "\n",
        "        # Setup section\n",
        "        heading(self.t(\"backup_setup_title\"))\n",
        "        lbl_d = tk.Label(page, text=self.t(\"backup_setup_desc\"),\n",
        "                         bg=C[\"bg\"], fg=C[\"desc\"],\n",
        "                         font=(FONT, 10), justify=tk.LEFT, anchor=\"nw\")\n",
        "        lbl_d.pack(fill=tk.X, padx=BP + 4, pady=(0, 10))\n",
        "        lbl_d.bind(\"<Configure>\", lambda e, l=lbl_d: l.configure(wraplength=max(100, e.width - 2)))\n",
        "\n",
        "        tk.Label(page, text=self.t(\"backup_current_label\"),\n",
        "                 bg=C[\"bg\"], fg=C[\"muted\"],\n",
        "                 font=(FONT, 9), anchor=\"w\").pack(fill=tk.X, padx=BP, pady=(4, 2))\n",
        "\n",
        "        path_lbl = tk.Label(page,\n",
        "                            text=self.backup_path or self.t(\"backup_ph\"),\n",
        "                            bg=C[\"card\"],\n",
        "                            fg=C[\"success\"] if self.backup_path else C[\"muted\"],\n",
        "                            font=(FONT, 9), anchor=\"w\", padx=12, pady=10)\n",
        "        path_lbl.pack(fill=tk.X, padx=BP, pady=(0, 8))\n",
        "        path_lbl.bind(\"<Configure>\",\n",
        "                      lambda e, l=path_lbl: l.configure(wraplength=max(100, e.width - 24)))\n",
        "\n",
        "        def pick():\n",
        "            p = filedialog.askdirectory()\n",
        "            if p:\n",
        "                self.backup_path = p\n",
        "                self._save_config()\n",
        "                n = sum(1 for f in os.listdir(p) if f.endswith(\".zip\"))\n",
        "                path_lbl.config(text=f\"✓  {p}  ({n} .zip files found)\", fg=C[\"success\"])\n",
        "\n",
        "        def save_close():\n",
        "            if not self.backup_path:\n",
        "                messagebox.showwarning(self.t(\"backup_win_title\"), self.t(\"no_backup_path\"))\n",
        "                return\n",
        "            self._save_config()\n",
        "            messagebox.showinfo(self.t(\"success\"), self.t(\"backup_saved_msg\"))\n",
        "            win.destroy()\n",
        "\n",
        "        ttk.Button(page, text=self.t(\"browse_backup\"), command=pick).pack(\n",
        "            fill=tk.X, padx=BP, pady=(0, 8))\n",
        "        ttk.Button(page, text=self.t(\"save_backup\"), command=save_close,\n",
        "                   style=\"Accent.TButton\").pack(fill=tk.X, padx=BP, pady=(0, 6))\n",
        "        ttk.Button(page, text=self.t(\"backup_cancel\"), command=win.destroy).pack(\n",
        "            fill=tk.X, padx=BP, pady=(0, 24))\n",
        "\n",
        "\n",
        "def main():\n",
        "    root = tk.Tk()\n",
        "    _app = App(root)\n",
        "    root.mainloop()\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ]
    }
  ]
}